name: Crystal CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Checks the code formatting
        run: crystal tool format --check
      -name: Checks the code with the static analyzer
        run: bin/ameba
      - name: Run tests
        run: crystal spec